/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/Categories`; params?: Router.UnknownInputParams; } | { pathname: `/Homepage`; params?: Router.UnknownInputParams; } | { pathname: `/Location_page`; params?: Router.UnknownInputParams; } | { pathname: `/Product_page`; params?: Router.UnknownInputParams; } | { pathname: `/StoreSelectionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VerifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/Select_address`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/subcategories/[categoryName]`, params: Router.UnknownInputParams & { categoryName: string | number; } } | { pathname: `/widelisting/[subcategoryName]`, params: Router.UnknownInputParams & { subcategoryName: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Cart`; params?: Router.UnknownOutputParams; } | { pathname: `/Categories`; params?: Router.UnknownOutputParams; } | { pathname: `/Homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/Location_page`; params?: Router.UnknownOutputParams; } | { pathname: `/Product_page`; params?: Router.UnknownOutputParams; } | { pathname: `/StoreSelectionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/VerifyEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/Select_address`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/subcategories/[categoryName]`, params: Router.UnknownOutputParams & { categoryName: string; } } | { pathname: `/widelisting/[subcategoryName]`, params: Router.UnknownOutputParams & { subcategoryName: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Cart${`?${string}` | `#${string}` | ''}` | `/Categories${`?${string}` | `#${string}` | ''}` | `/Homepage${`?${string}` | `#${string}` | ''}` | `/Location_page${`?${string}` | `#${string}` | ''}` | `/Product_page${`?${string}` | `#${string}` | ''}` | `/StoreSelectionScreen${`?${string}` | `#${string}` | ''}` | `/VerifyEmail${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `/Select_address${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/Categories`; params?: Router.UnknownInputParams; } | { pathname: `/Homepage`; params?: Router.UnknownInputParams; } | { pathname: `/Location_page`; params?: Router.UnknownInputParams; } | { pathname: `/Product_page`; params?: Router.UnknownInputParams; } | { pathname: `/StoreSelectionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VerifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/Select_address`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `/subcategories/${Router.SingleRoutePart<T>}` | `/widelisting/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/subcategories/[categoryName]`, params: Router.UnknownInputParams & { categoryName: string | number; } } | { pathname: `/widelisting/[subcategoryName]`, params: Router.UnknownInputParams & { subcategoryName: string | number; } };
    }
  }
}
